version: "3.8"

services:
  db:
    image: postgres:16
    container_name: cloud-admin-db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app_pass
      POSTGRES_DB: app_db
    volumes:
      - cloud_admin_pgdata:/var/lib/postgresql/data
    networks:
      - cloud-admin-net

  app:
    build: .
    image: cloud-admin-panel:latest
    container_name: cloud-admin
    depends_on:
      - db
    ports:
      - "6006:6005"
    env_file:
      - .env
    networks:
      - cloud-admin-net

volumes:
  cloud_admin_pgdata:

networks:
  cloud-admin-net:
